import '../models/sura_model.dart';

class Constants{

  List<String> arabicAuranSuras = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];
  List<String> englishQuranSurahs = [
    "Al-Fatiha",
    "Al-Baqarah",
    "Aal-E-Imran",
    "An-Nisa'",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu'minun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shu'ara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajda",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jathiya",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'a",
    "Al-Hadid",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahina",
    "As-Saff",
    "Al-Jumu'a",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddathir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba'",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Duha",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyina",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari'a",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma'un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas"
  ];
  List<String> ayaNumber = [
    '7',
    '286',
    '200',
    '176',
    '120',
    '165',
    '206',
    '75',
    '129',
    '109',
    '123',
    '111',
    '43',
    '52',
    '99',
    '128',
    '111',
    '110',
    '98',
    '135',
    '112',
    '78',
    '118',
    '64',
    '77',
    '227',
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '5',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '6',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6'
  ];

  static List<SuraModel> suraList = [
    SuraModel(arName: "الفاتحه", enName: "Al-Fatiha", suraNumber: 1, verses: 7),
    SuraModel(arName: "البقرة", enName: "Al-Baqarah", suraNumber: 2, verses: 286),
    SuraModel(arName: "آل عمران", enName: "Aal-E-Imran", suraNumber: 3, verses: 200),
    SuraModel(arName: "النساء", enName: "An-Nisa'", suraNumber: 4, verses: 176),
    SuraModel(arName: "المائدة", enName: "Al-Ma'idah", suraNumber: 5, verses: 120),
    SuraModel(arName: "الأنعام", enName: "Al-An'am", suraNumber: 6, verses: 165),
    SuraModel(arName: "الأعراف", enName: "Al-A'raf", suraNumber: 7, verses: 206),
    SuraModel(arName: "الأنفال", enName: "Al-Anfal", suraNumber: 8, verses: 75),
    SuraModel(arName: "التوبة", enName: "At-Tawbah", suraNumber: 9, verses: 129),
    SuraModel(arName: "يونس", enName: "Yunus", suraNumber: 10, verses: 109),
    SuraModel(arName: "هود", enName: "Hud", suraNumber: 11, verses: 123),
    SuraModel(arName: "يوسف", enName: "Yusuf", suraNumber: 12, verses: 111),
    SuraModel(arName: "الرعد", enName: "Ar-Ra'd", suraNumber: 13, verses: 43),
    SuraModel(arName: "إبراهيم", enName: "Ibrahim", suraNumber: 14, verses: 52),
    SuraModel(arName: "الحجر", enName: "Al-Hijr", suraNumber: 15, verses: 99),
    SuraModel(arName: "النحل", enName: "An-Nahl", suraNumber: 16, verses: 128),
    SuraModel(arName: "الإسراء", enName: "Al-Isra", suraNumber: 17, verses: 111),
    SuraModel(arName: "الكهف", enName: "Al-Kahf", suraNumber: 18, verses: 110),
    SuraModel(arName: "مريم", enName: "Maryam", suraNumber: 19, verses: 98),
    SuraModel(arName: "طه", enName: "Ta-Ha", suraNumber: 20, verses: 135),
    SuraModel(arName: "الأنبياء", enName: "Al-Anbiya", suraNumber: 21, verses: 112),
    SuraModel(arName: "الحج", enName: "Al-Hajj", suraNumber: 22, verses: 78),
    SuraModel(arName: "المؤمنون", enName: "Al-Mu'minun", suraNumber: 23, verses: 118),
    SuraModel(arName: "النّور", enName: "An-Nur", suraNumber: 24, verses: 64),
    SuraModel(arName: "الفرقان", enName: "Al-Furqan", suraNumber: 25, verses: 77),
    SuraModel(arName: "الشعراء", enName: "Ash-Shu'ara", suraNumber: 26, verses: 227),
    SuraModel(arName: "النّمل", enName: "An-Naml", suraNumber: 27, verses: 93),
    SuraModel(arName: "القصص", enName: "Al-Qasas", suraNumber: 28, verses: 88),
    SuraModel(arName: "العنكبوت", enName: "Al-Ankabut", suraNumber: 29, verses: 69),
    SuraModel(arName: "الرّوم", enName: "Ar-Rum", suraNumber: 30, verses: 60),
    SuraModel(arName: "لقمان", enName: "Luqman", suraNumber: 31, verses: 34),
    SuraModel(arName: "السجدة", enName: "As-Sajda", suraNumber: 32, verses: 30),
    SuraModel(arName: "الأحزاب", enName: "Al-Ahzab", suraNumber: 33, verses: 73),
    SuraModel(arName: "سبأ", enName: "Saba", suraNumber: 34, verses: 54),
    SuraModel(arName: "فاطر", enName: "Fatir", suraNumber: 35, verses: 45),
    SuraModel(arName: "يس", enName: "Ya-Sin", suraNumber: 36, verses: 83),
    SuraModel(arName: "الصافات", enName: "As-Saffat", suraNumber: 37, verses: 182),
    SuraModel(arName: "ص", enName: "Sad", suraNumber: 38, verses: 88),
    SuraModel(arName: "الزمر", enName: "Az-Zumar", suraNumber: 39, verses: 75),
    SuraModel(arName: "غافر", enName: "Ghafir", suraNumber: 40, verses: 85),
    SuraModel(arName: "فصّلت", enName: "Fussilat", suraNumber: 41, verses: 54),
    SuraModel(arName: "الشورى", enName: "Ash-Shura", suraNumber: 42, verses: 53),
    SuraModel(arName: "الزخرف", enName: "Az-Zukhruf", suraNumber: 43, verses: 89),
    SuraModel(arName: "الدّخان", enName: "Ad-Dukhan", suraNumber: 44, verses: 59),
    SuraModel(arName: "الجاثية", enName: "Al-Jathiya", suraNumber: 45, verses: 37),
    SuraModel(arName: "الأحقاف", enName: "Al-Ahqaf", suraNumber: 46, verses: 35),
    SuraModel(arName: "محمد", enName: "Muhammad", suraNumber: 47, verses: 38),
    SuraModel(arName: "الفتح", enName: "Al-Fath", suraNumber: 48, verses: 29),
    SuraModel(arName: "الحجرات", enName: "Al-Hujurat", suraNumber: 49, verses: 18),
    SuraModel(arName: "ق", enName: "Qaf", suraNumber: 50, verses: 45),
    SuraModel(arName: "الذاريات", enName: "Adh-Dhariyat", suraNumber: 51, verses: 60),
    SuraModel(arName: "الطور", enName: "At-Tur", suraNumber: 52, verses: 49),
    SuraModel(arName: "النجم", enName: "An-Najm", suraNumber: 53, verses: 62),
    SuraModel(arName: "القمر", enName: "Al-Qamar", suraNumber: 54, verses: 55),
    SuraModel(arName: "الرحمن", enName: "Ar-Rahman", suraNumber: 55, verses: 78),
    SuraModel(arName: "الواقعة", enName: "Al-Waqi'a", suraNumber: 56, verses: 96),
    SuraModel(arName: "الحديد", enName: "Al-Hadid", suraNumber: 57, verses: 29),
    SuraModel(arName: "المجادلة", enName: "Al-Mujadila", suraNumber: 58, verses: 22),
    SuraModel(arName: "الحشر", enName: "Al-Hashr", suraNumber: 59, verses: 24),
    SuraModel(arName: "الممتحنة", enName: "Al-Mumtahina", suraNumber: 60, verses: 13),
    SuraModel(arName: "الصف", enName: "As-Saff", suraNumber: 61, verses: 14),
    SuraModel(arName: "الجمعة", enName: "Al-Jumu'a", suraNumber: 62, verses: 11),
    SuraModel(arName: "المنافقون", enName: "Al-Munafiqun", suraNumber: 63, verses: 11),
    SuraModel(arName: "التغابن", enName: "At-Taghabun", suraNumber: 64, verses: 18),
    SuraModel(arName: "الطلاق", enName: "At-Talaq", suraNumber: 65, verses: 12),
    SuraModel(arName: "التحريم", enName: "At-Tahrim", suraNumber: 66, verses: 12),
    SuraModel(arName: "الملك", enName: "Al-Mulk", suraNumber: 67, verses: 30),
    SuraModel(arName: "القلم", enName: "Al-Qalam", suraNumber: 68, verses: 52),
    SuraModel(arName: "الحاقة", enName: "Al-Haqqah", suraNumber: 69, verses: 52),
    SuraModel(arName: "المعارج", enName: "Al-Ma'arij", suraNumber: 70, verses: 44),
    SuraModel(arName: "نوح", enName: "Nuh", suraNumber: 71, verses: 28),
    SuraModel(arName: "الجن", enName: "Al-Jinn", suraNumber: 72, verses: 28),
    SuraModel(arName: "المزّمّل", enName: "Al-Muzzammil", suraNumber: 73, verses: 20),
    SuraModel(arName: "المدّثر", enName: "Al-Muddathir", suraNumber: 74, verses: 56),
    SuraModel(arName: "القيامة", enName: "Al-Qiyamah", suraNumber: 75, verses: 40),
    SuraModel(arName: "الإنسان", enName: "Al-Insan", suraNumber: 76, verses: 31),
    SuraModel(arName: "المرسلات", enName: "Al-Mursalat", suraNumber: 77, verses: 50),
    SuraModel(arName: "النبأ", enName: "An-Naba'", suraNumber: 78, verses: 40),
    SuraModel(arName: "النازعات", enName: "An-Nazi'at", suraNumber: 79, verses: 46),
    SuraModel(arName: "عبس", enName: "Abasa", suraNumber: 80, verses: 42),
    SuraModel(arName: "التكوير", enName: "At-Takwir", suraNumber: 81, verses: 29),
    SuraModel(arName: "الإنفطار", enName: "Al-Infitar", suraNumber: 82, verses: 19),
    SuraModel(arName: "المطفّفين", enName: "Al-Mutaffifin", suraNumber: 83, verses: 36),
    SuraModel(arName: "الإنشقاق", enName: "Al-Inshiqaq", suraNumber: 84, verses: 25),
    SuraModel(arName: "البروج", enName: "Al-Buruj", suraNumber: 85, verses: 22),
    SuraModel(arName: "الطارق", enName: "At-Tariq", suraNumber: 86, verses: 17),
    SuraModel(arName: "الأعلى", enName: "Al-A'la", suraNumber: 87, verses: 19),
    SuraModel(arName: "الغاشية", enName: "Al-Ghashiyah", suraNumber: 88, verses: 26),
    SuraModel(arName: "الفجر", enName: "Al-Fajr", suraNumber: 89, verses: 30),
    SuraModel(arName: "البلد", enName: "Al-Balad", suraNumber: 90, verses: 20),
    SuraModel(arName: "الشمس", enName: "Ash-Shams", suraNumber: 91, verses: 15),
    SuraModel(arName: "الليل", enName: "Al-Lail", suraNumber: 92, verses: 21),
    SuraModel(arName: "الضحى", enName: "Ad-Duha", suraNumber: 93, verses: 11),
    SuraModel(arName: "الشرح", enName: "Ash-Sharh", suraNumber: 94, verses: 8),
    SuraModel(arName: "التين", enName: "At-Tin", suraNumber: 95, verses: 8),
    SuraModel(arName: "العلق", enName: "Al-Alaq", suraNumber: 96, verses: 19),
    SuraModel(arName: "القدر", enName: "Al-Qadr", suraNumber: 97, verses: 5),
    SuraModel(arName: "البينة", enName: "Al-Bayyina", suraNumber: 98, verses: 8),
    SuraModel(arName: "الزلزلة", enName: "Az-Zalzalah", suraNumber: 99, verses: 8),
    SuraModel(arName: "العاديات", enName: "Al-Adiyat", suraNumber: 100, verses: 11),
    SuraModel(arName: "القارعة", enName: "Al-Qari'a", suraNumber: 101, verses: 11),
    SuraModel(arName: "التكاثر", enName: "At-Takathur", suraNumber: 102, verses: 8),
    SuraModel(arName: "العصر", enName: "Al-Asr", suraNumber: 103, verses: 3),
    SuraModel(arName: "الهمزة", enName: "Al-Humazah", suraNumber: 104, verses: 9),
    SuraModel(arName: "الفيل", enName: "Al-Fil", suraNumber: 105, verses: 5),
    SuraModel(arName: "قريش", enName: "Quraysh", suraNumber: 106, verses: 4),
    SuraModel(arName: "الماعون", enName: "Al-Ma'un", suraNumber: 107, verses: 7),
    SuraModel(arName: "الكوثر", enName: "Al-Kawthar", suraNumber: 108, verses: 3),
    SuraModel(arName: "الكافرون", enName: "Al-Kafirun", suraNumber: 109, verses: 6),
    SuraModel(arName: "النصر", enName: "An-Nasr", suraNumber: 110, verses: 3),
    SuraModel(arName: "المسد", enName: "Al-Masad", suraNumber: 111, verses: 5),
    SuraModel(arName: "الإخلاص", enName: "Al-Ikhlas", suraNumber: 112, verses: 4),
    SuraModel(arName: "الفلق", enName: "Al-Falaq", suraNumber: 113, verses: 5),
    SuraModel(arName: "الناس", enName: "An-Nas", suraNumber: 114, verses: 6),
  ];


}